/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    kotlin("multiplatform") apply false
    kotlin("plugin.serialization") apply false
}

allprojects {
    group = "moe.nikky"
    version = "1.0-SNAPSHOT"

    repositories {
        mavenCentral()
    }
}

tasks {
    val subprojects = listOf(
        project(":traktor-convert"),
        project(":rekordbox-export"),
        project(":mixxx-export"),
        project(":virtualdj-export"),
    )
    val packageZip by registering(Zip::class) {
        group = "package"
        subprojects.forEach { subproject ->
//            dependsOn(it.tasks["linkDebugExecutableMingwX64"])
            from(subproject.tasks["linkReleaseExecutableMingwX64"])
        }
        archiveBaseName = "dist"
        destinationDirectory = project.layout.buildDirectory
    }
    val copyExecutables by registering(Copy::class) {
        group = "package"
        subprojects.forEach { subproject ->
//            dependsOn(it.tasks["linkDebugExecutableMingwX64"])
            from(subproject.tasks["linkReleaseExecutableMingwX64"])
        }
        destinationDir = file(project.layout.buildDirectory)
    }
}
