/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
    // See https://jmfayard.github.io/refreshVersions
    id("de.fayard.refreshVersions") version "0.60.5"
}

rootProject.name = "setlist-export"

include("shared")
include("traktor")
include("rekordbox")
include("mixxx")

project(":traktor").name = "traktor-export-converter"
project(":rekordbox").name = "rekordbox-export"
project(":mixxx").name = "mixxx-export"